### ISSUE TITLE
Throw a RangeError when startDate is greater than endDate

### ISSUE THREAD

**Issue by fabalbon** [fabalbon/proposal-intl-DateTimeFormat-formatRange#1]
Should `formatRange(startDate, endDate)` and `formatRangeToParts(startDate, endDate)` throw a **RangeError** if _startDate_ is a later datetime than _endDate_?

1. [CLDR](https://unicode.org/reports/tr35/tr35-dates.html#intervalFormats) is not explicit about this. It mentions that there is a _start datetime_ and a _end datetime_, but it never explicitly mentions that _start datetime_ has to be an earlier datetime than _end datetime_,
1. ICU4J formats the date interval independent of which date is earlier (e.g. 'May 20 – 10, 2018')

**Comment by fabalbon** [comment]
cc @littledan

**Comment by littledan** [comment]
What does ICU4C do?

**Comment by fabalbon** [comment]
ICU will format both dates in order regardless of which one is the earlier or later date. For example, in ICU4J:

```java
StringBuffer str = new StringBuffer();
DateIntervalFormat fmt = 
    DateIntervalFormat.getInstance("yMMMEd", new ULocale("en"));
fmt.format(
    new DateInterval(1000L*3600*24*8, 1000L*3600*24*4), 
    str, 
    DontCareFieldPosition.INSTANCE);
// str --> "Thu, Jan 8 – Sun, Jan 4, 1970"
```

**Comment by sffc** [comment]
How about putting the dates in order?

You might have a case where you have a date in the past (or future) and want to format an interval relative to that date, and this could be useful.

This feels JavaScripty to me and is consistent with how functions like substring work.  Quote from [MDN for substring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring):

> substring() extracts characters from indexStart up to but not including indexEnd. In particular:
> 
> - If indexEnd is omitted, substring() extracts characters to the end of the string.
> - If indexStart is equal to indexEnd, substring() returns an empty string.
> - If indexStart is greater than indexEnd, then the effect of substring() is as if the two arguments were swapped; See example below.

**Comment by fabalbon** [comment]
We discussed this in the January 2019 Ecma402 monthly call and we agreed to throw a RangeError when startDate is greater than endDate.

We could potentially relax this restriction (and put the dates in order) on a second version.

**Comment by nathanhammond** [comment]
There is a built-in assumption here that communicating about the dates in chronological order is correct. I would like to challenge that assumption.

"The ten days previous to the 520 calamity, `May 20 – 10, 2018` served notice to ..."
"The months leading up to the crash, `June - March, 2018` ..."

These are both somewhat strange in English but they:
- May be more expressive of the authors intent.
- Maps to the behavior that we see in ICU4J.
- Doesn't make assumptions that the author has screwed it up.
- Function correctly in terms of the collapsing.

I'm comfortable starting with a `RangeError` (to confirm that these use cases exist before committing to support them) but I would be rather opposed to reordering them for the author as that implies knowledge of the author's intent.

**Comment by fabalbon** [comment]
We discussed this issue in the Feb 2019 Ecma402 monthly call.

People are still divided whether we should enforce a particular order, but, for the moment we agreed that on a first version we will throw a RangeError when startDate is greater than endDate.

I'll close this issue for now. We can revisit later.
