### ISSUE TITLE
Default behavior when date parameter is undefined.

### ISSUE THREAD

**Issue by fabalbon** [fabalbon/proposal-intl-DateTimeFormat-formatRange#2]
Which should be the default behavior of `formatRange(startDate, endDate)` and `formatRangeToParts(startDate, endDate)` when either `startDate` or `endDate` is `undefined`?

Currently `format(date)` and `formatToParts(date)` will use `Date.now` if the `date` parameter is `undefined`.

**Alternative 1:** Use `Date.now` when either `startDate` or `endDate` is `undefined`.

This would be consistent with `format(date)`, but the behavior is somewhat confusing: it's not immediately clear what happens when you provide just one parameter (the second `undefined`), or if you provide `undefined` as the first parameter and a date on the second.

**Alternative 2:** Throw **RangeError** if either `startDate` or `endDate` is `undefined`.

It is less flexible when one of the parameters is not provided but the behavior is more straightforward.

**Comment by fabalbon** [comment]
cc @littledan

**Comment by littledan** [comment]
Thanks for filing this issue. I vote Alternative 2! Let's discuss the question in the Intl call this week.

**Comment by sffc** [comment]
How about if you have a single argument, use Date.now as the other argument, and order them so that if you pass a date in the past, then you get a range from the past date to now, and if you pass a date in the future, then you get a range from now to the future date?

**Comment by nathanhammond** [comment]
I'm of the opinion that `RangeError` is the right solution here. ([Related to my comment here.](https://github.com/fabalbon/proposal-intl-DateTimeFormat-formatRange/issues/1#issuecomment-463024572))

**Comment by fabalbon** [comment]
> How about if you have a single argument, use Date.now as the other argument, and order them so that if you pass a date in the past, then you get a range from the past date to now, and if you pass a date in the future, then you get a range from now to the future date?

I also believe RangeError is a better option here. We still haven't reached a consensus whether dates should always be displayed in a chronological order (Issue #1), therefore we should refrain from doing so here until we revisit Issue #1.

For the moment, throwing a RangeError is the most conservative approach, and it was the consensus when this issue was discussed at the July 2018 ECMA 402 call. I'll close this issue for now. We can revisit this later.
