### ISSUE TITLE
How to handle eras?

### ISSUE THREAD

**Issue by sffc** [fabalbon/proposal-intl-DateTimeFormat-formatRange#27]
From 2020-09-10 meeting:

> FYT: Are eras problematic?  For example, what happens when crossing a Japanese era boundary?  Or when crossing from BC to AD?  I want to make sure your current spec handles this.  If there's a bug, we should fix it in ICU.
>
> FBN: That should be handled in the spec.  I should verify.

Also see https://github.com/tc39/proposal-intl-DateTimeFormat-formatRange/issues/22#issuecomment-658147276

**Comment by fabalbon** [comment]
I reviewed the current spec text and double checked that date intervals that cross the Era boundary are being handled correctly.

The issue described in https://github.com/tc39/proposal-intl-DateTimeFormat-formatRange/issues/22#issuecomment-658147276 is an ICU bug that impacts ICU-based implementations. This is currently being tracked in [ICU-21222](https://unicode-org.atlassian.net/browse/ICU-21222).

cc: @FrankYFTang
