### ISSUE TITLE
Spec difference does not seem to be rebased off of latest ECMA402

### ISSUE THREAD

**Issue by longlho** [fabalbon/proposal-intl-DateTimeFormat-formatRange#29]
http://tc39.es/proposal-intl-DateTimeFormat-formatRange/#sec-formatdatetimepattern seems to be missing `relatedYear`, `yearName` & the fallback `unknown` parts.

**Comment by fabalbon** [comment]
424cb21 merged the latest version in https://github.com/tc39/ecma402/pull/347 which already includes `relatedYear`, `yearName` & the `unknown` parts. Once that PR is merged we will do a rebase off of the latest ECMA 402 spec.
