### ISSUE TITLE
DateTimeFormat options

### ISSUE THREAD

**Issue by devsnek** [fabalbon/proposal-intl-DateTimeFormat-formatRange#3]
Intl.DateTimeFormat has a whole bunch of options, are those represented here? it seems like more configurability is needed

example:
- `July 24 - 27, 2018`
- `Jul 24 - 27, 2018`
- `July 24 - 27, 18`
- `July 24 - July 27, 2018`

**Comment by sffc** [comment]
The "Jul" vs "July" should be controlled by the `month` option in DateTimeFormat.  The more interesting question is how to control whether you repeat the month/year even if it would be redundant.

Somewhat related: [an API I proposed](https://unicode-org.atlassian.net/browse/ICU-11276?focusedCommentId=41044&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-41044) for currency range formatting in ICU.  I added a knob called `collapse` to support this for currency ranges (for example, "$3-5" or "$3-$5").  If we wanted to add an option for this, it could be called something like `rangeCollapse` on the main DateTimeFormat options object.

**Comment by fabalbon** [comment]
As @sffc mentioned, there are two types of configuration options in the examples given by @devsnek:
1) Control the display length of each calendar field.
2) Being able to expand or collapse fields in the formatted range.

**1.** This is already being controlled through the options object when instantiating a new `Intl.DateTimeFormat`. For example:

- `{year: 'numeric', month: 'long', day: 'numeric'}` --> `July 24 - 27, 2018`
- `{year: '2-digit', month: 'short', day: 'numeric'}` --> `Jul 24 - 27, 18`

**2.** Currently, the formatter will choose the date interval pattern solely based on which is the largest different calendar fields between the two dates. This follows the rules defined in [TR-35](https://unicode.org/reports/tr35/tr35-dates.html#intervalFormats) with the goal of formatting the range as concisely as possible.

For example, for `{year: 'numeric', month: 'short', day: 'numeric'}`, the interval patterns are:

`y: 'MMM dd, y - MMM dd, y'`
`M: 'MMM dd - MMM dd, y'`
`d: 'MMM dd - dd, y'`

If the _day_ is the largest different calendar field, the interval will be formatted with the `d` pattern, producing: `Jul 24 - 27, 2018`.

A possible way to 'expand' the formatted interval could be to force the use of the interval pattern for a larger calendar field, such as for `M`, producing: `Jul 24 - Jul 27, 2018`. 

Based on @sffc's suggestion,  we could add a new option (`rangeCollapse`) for this. The user could use it to indicate the smallest calendar field for which they want to use an interval pattern. Something like:

- `{year: 'numeric', month: 'long', day: 'numeric'}` --> `July 24 - 27, 2018`
- `{year: 'numeric', month: 'long', day: 'numeric', rangeCollapse: 'month'}` --> `July 24 - July 27, 2018`
- `{year: 'numeric', month: 'long', day: 'numeric', rangeCollapse: 'year'}` --> `July 24, 2018 - July 27, 2018`

**Comment by sffc** [comment]
For **rangeCollapse** setting names, I would expect "month" to mean that months and higher are collapsed, rather than @fabalbon's suggested behavior, which seems to be "stop before the month".  To start the discussion, I think good names could be:

- Most aggressive collapse behavior: "all", "auto", "day"
  - i.e., `July 24 – 27, 2018`
- Less aggressive: "year", "year-only"
  - i.e., `July 24 – July 27, 2018`
- No collapsing: "none", "disabled", "no-collapse"
  - i.e., `July 24, 2018 – July 27, 2018`

Note: the word "collapse" is also used in the CSS [border-collapse](https://developer.mozilla.org/en-US/docs/Web/CSS/border-collapse) property.

**Comment by sffc** [comment]
Another question: how does this work with non-Gregorian calendars?  Or is that out of scope for date interval formatting?

**Comment by fabalbon** [comment]
We discussed the `rangeCollapse` option in the Feb 2019 ECMA-402 meeting. It was decided to leave it out for now, as there is no clear demand for it.

Closing this issue for now, we can revisit this on a second version.
