### ISSUE TITLE
Editorial: Typos

### ISSUE THREAD

**Issue by leobalter** [fabalbon/proposal-intl-DateTimeFormat-formatRange#5]
In [PartitionDateTimeRangePattern](https://rawgit.com/fabalbon/proposal-intl-DateTimeFormat-formatRange/master/out/#sec-partitiondatetimerangepattern) when it reads:

`If fieldName is equal to AmPm, then`

it should be `If fieldName is equal to [[AmPm]], then`, right?

**Comment by leobalter** [comment]
Some others:

on the [internal slots](https://rawgit.com/fabalbon/proposal-intl-DateTimeFormat-formatRange/master/out/#sec-intl.datetimeformat-internal-slots)

When it reads:

`A rangePatterns field with a Record value`

should be `A rangePattern field with a Record value` (rangePattern, singular)

**Comment by leobalter** [comment]
I might be wrong and please disregard the issue in this case.

**Comment by fabalbon** [comment]
> it should be `If fieldName is equal to [[AmPm]], then`, right?

Thanks!

> should be `A rangePattern field with a Record value` (rangePattern, singular)

It should be plural, because it is a Record containing all range patterns for a specific set of options. In fact, there was a typo in `EXAMPLE` where we were using `rangePattern` and `rangePattern12` instead of `rangePatterns` and `rangePatterns12`.
