### ISSUE TITLE
Editor review sign-off for Stage 3

### ISSUE THREAD

**Issue by leobalter** [fabalbon/proposal-intl-DateTimeFormat-formatRange#6]
+1 to advance this proposal. The current draft looks good to me. I only pointed minor editorial issues - see #5 - but should not be blockers.

**Comment by leobalter** [comment]
BTW, can we move this repo to TC39? We'd need to first transfer it to the tc39-transfer org.

**Comment by nathanhammond** [comment]
I have also reviewed this in detail and see no blocking issues (with two minor editorial comments in #8). This is my signoff and endorsement for advancement.

**Comment by gsathya** [comment]
LGTM from my side

**Comment by FrankYFTang** [comment]
The v8 implementation is done and is going to ship this with chrome m76 soon.

**Comment by fabalbon** [comment]
Closing this issue. The proposal advanced to Stage 3 and now is getting ready for Stage 4.
